package:
  name: conda-launch
  version: 0.2

#source:
#  git_url: git@github.com:conda/conda-launch.git
#  git_tag: 0.2

requirements:
  build:
    - python
  run:
    - python
    - ipython
    - ipython-notebook
    - setuptools
    - flask
    - requests
    - psutil
    - runipy
    - conda-api

test:
  commands:
    - conda-appserver -h
    - conda-launch -h
  imports:
    - ipyapp

about:
  home: https://github.com/conda/conda-api
  license: BSD
